# Generated by Django 5.2.12 on 2026-03-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_codehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codehistory',
            old_name='code',
            new_name='input_code',
        ),
        migrations.RenameField(
            model_name='codehistory',
            old_name='result',
            new_name='output_result',
        ),
        migrations.AddField(
            model_name='codehistory',
            name='action_type',
            field=models.CharField(default='Code Review', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codehistory',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
